# Site settings
title: Sara Burns
email: sburns at wellesley dot edu
description: > # this means to ignore newlines until "baseurl:"
  A  place to discuss technology, education, travel, and more.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://saraburns.github.io" # the base hostname & protocol for your site
twitter_username: sara_a_burns
github_username:  saraburns

# Build settings
markdown: kramdown
highlighter: pygments
